export const GET_IMAGES = 'GET_IMAGES';
export const CLEAR_IMAGES = 'CLEAR_IMAGES';
export const LOAD_SUBJECTS = 'LOAD_SUBJECTS';
export const GET_SUBJECT = 'GET_SUBJECT';
export const SET_SUBJECT = 'SET_SUBJECT';
export const LOAD_TRANSITIONS = 'LOAD_TRANSITIONS';
export const GET_TRANSITION = 'GET_TRANSITION';
export const SET_TRANSITION = 'SET_TRANSITION';
export const LOAD_TIMINGS = 'LOAD_TIMINGS';
export const GET_TIMING = 'GET_TIMING';
export const SET_TIMING = 'SET_TIMING';

export default {
  GET_IMAGES,
  CLEAR_IMAGES,
  LOAD_SUBJECTS,
  GET_SUBJECT,
  SET_SUBJECT,
  LOAD_TRANSITIONS,
  GET_TRANSITION,
  SET_TRANSITION,
  LOAD_TIMINGS,
  GET_TIMING,
  SET_TIMING,
};
