export const UPLOAD_PROFILE_PIC = 'UPLOAD_PROFILE_PIC';
export const GET_PROFILE_PIC = 'GET_PROFILE_PIC';
export const GET_COUNTRIES = 'GET_COUNTRIES';

export default {
  UPLOAD_PROFILE_PIC,
  GET_PROFILE_PIC,
  GET_COUNTRIES,
};
